name: Build

on:
  push:
    branches: main
    tags: 'v*'
  pull_request:
    branches: main

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  run-precommit:
    name: "pre-commit run --all-files"
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.1

      - name: Checkout
        uses: actions/checkout@v6

      - name: pre-commit run --all-files
        id: run-formatters
        run: |
          if ! nix-shell --run 'pre-commit run --all-files'; then
            git diff
            exit 1
          fi

  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release, Debug]
        config:
          # netpbm isn't available anywhere on Windows, needs POSIX headers
          #- name: "Windows (MSVC)"
          #  os: windows-latest
          #  compiler: msvc

          #- name: "Windows (MinGW)"
          #  os: windows-latest
          #  compiler: mingw

          - name: "macOS"
            os: macos-latest

          - name: "Linux"
            os: ubuntu-latest

    name: "${{ matrix.config.name }} - ${{ matrix.build-type }}"
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies [macOS]
        if: ${{ runner.os == 'macOS' }}
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update
          brew install netpbm

      - name: Install dependencies [Linux]
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install libnetpbm-dev valgrind

      - name: Configure
        run: |
          CONFIGURE_ARGS=(
            "-DCMAKE_INSTALL_PREFIX:STRING=${PWD}/target"
            "-DCMAKE_BUILD_TYPE:STRING=${{ matrix.build-type }}"
            "-DNETPBM2OSBADGEICONS_WERROR:BOOL=ON"
          )

          if [ "${{ runner.os }}" == "Linux" ]; then
            CONFIGURE_ARGS+=(
              "-DNETPBM2OSBADGEICONS_TEST_VALGRIND:BOOL=ON"
            )
          fi

          if [ "${{ matrix.config.compiler }}" == "mingw" ]; then
            CONFIGURE_ARGS+=(
              -G "MinGW Makefiles"
            )
          fi

          cmake -B build \
            "${CONFIGURE_ARGS[@]}"

      - name: Build
        run: |
          BUILD_ARGS=(
            --config "${{ matrix.build-type }}"
          )

          cmake --build build \
            "${BUILD_ARGS[@]}"

      - name: Test
        run: |
          TEST_ARGS=(
            --build-config "${{ matrix.build-type }}"
          )

          if [ "${{ matrix.build-type }}" == "Debug" ]; then
            TEST_ARGS+=(
              --verbose
            )
          fi

          ctest --test-dir build \
            "${TEST_ARGS[@]}"


      - name: Install
        run: |
          INSTALL_ARGS=(
            --config "${{ matrix.build-type }}"
          )

          cmake --install build \
            "${INSTALL_ARGS[@]}"
